177,0
V,Monge,6
S,PolynomialCompareLog,Compare two polynomials over a local field of the same degree by comparing the discrete logarithms of the coefficients and using lexicographic ordering with leading coefficient first,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,ResidialPolyCompare,"Return 1 if A>B, -1 if A<B, 0 otherwise",0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,ResidualPolyDistinguished,"The distinguished (minimal) representative of the residual polynomial class of an Eisenstein polynomial phi along with Eisenstein polynomials psi that yield the distinguished representative. If conjugates is true, the conjugates under AutomorphismGroup(CoefficientRing(phi)) are also considered. If constant_first is true, it is first assured that the dicrete logarithm of the constant coefficiant of psi is minimal and only afterwards the residual polynomials are minimized",0,1,0,0,0,0,0,0,0,312,,-1,-38,-38,-38,-38,-38
S,Distinguished,"Given a set of reduced nu-Oystein polynomials, return the distinguished polynomial",1,0,1,83,1,312,0,395,1,0,0,0,0,0,0,0,83,,-1,-38,-38,-38,-38,-38
S,PolRedPadicTame,Reduction of a tamely ramified polynomial,0,1,0,0,0,0,0,0,0,312,,-1,-38,-38,-38,-38,-38
S,PolRedPadicTame,,0,3,0,0,0,0,0,0,0,-1,,0,0,312,,0,0,312,,-1,-38,-38,-38,-38,-38
S,PolRedPadic,"Phi in Zp[x] in Eisenstein Form, Phi(alpha)=0, nu(alpha) uniformizer of Qp(alpha), return the Krasner- Monge reduction of Phi",0,3,0,0,0,0,0,0,0,-1,,0,0,312,,0,0,312,,-1,-38,-38,-38,-38,-38
S,PolRedPadic,For Phi in O_L irreducible return a Krasner-Monge reduced polynomial Psi such that L[x]/(Phi)=K[x]/(Psi),0,2,0,0,0,0,0,0,0,395,,0,0,312,,-1,-38,-38,-38,-38,-38
S,PolRedPadic,For Phi in OK irreducible return a Krasner-Monge reduced polynomial Psi such that K[x]/(Phi)=K[x]/(Psi),0,1,0,0,0,0,0,0,0,312,,-1,-38,-38,-38,-38,-38
S,PolRedPadic,The distinguished reduced generating polynomial of the extension generated by f over Zp,1,0,1,312,0,319,2,0,0,0,0,0,0,0,148,,0,0,312,,-1,-38,-38,-38,-38,-38
