177,0
V,Rampoly,6
S,RamificationPoly,"Ramification polygon and polynomial phi(alpha+nu(alpha)x) of a nu-Oystein polynomial phi, where alpha is a root of phi",0,3,0,0,0,0,0,0,0,396,,0,0,312,,0,0,312,,-1,-38,-38,-38,-38,-38
S,RamificationPoly,Ramification polygon and polynomial of the extension defined by phi,0,1,0,0,0,0,0,0,0,312,,-1,-38,-38,-38,-38,-38
S,HasseHerbrand,"e*Phi(m), where Phi is the Hasse Herbrand function of the ramification polygon R",0,2,0,0,0,0,0,0,0,-1,,0,0,200,,-1,-38,-38,-38,-38,-38
S,HasseHerbrand,"e*Phi(m), where Phi is the Hasse Herbrand function of the ramification polygon R",0,2,0,0,0,0,0,0,0,-1,,0,0,312,,-1,-38,-38,-38,-38,-38
S,AdditiveResidualPoly,The residual polynomial of the segment of the ramfication polygon of phi of slope m and e times the Hasse Herbrand function of phi at m. alpha is a root of phi and nu(alpha) a uniformizing element in the extension definied by phi with deg(phi)=e*deg(nu),0,4,0,0,0,0,0,0,0,148,,0,0,396,,0,0,312,,0,0,312,,-1,-38,-38,-38,-38,-38
S,ResidualPolys,The residual polynomials of the segments of the ramfication polygon of phi. alpha is a root of phi and nu(alpha) a uniformizing element in the extensions generated by alpha,0,3,0,0,0,0,0,0,0,396,,0,0,312,,0,0,312,,-1,-38,-38,-38,-38,-38
S,ResidualPolys,The residual polynomials of the segments of the ramfication polygon of phi,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,ResidualPolyClasses,The residual polynomial classes of an Eisenstein polynomial phi,0,1,0,0,0,0,0,0,0,312,,-1,-38,-38,-38,-38,-38
