{
  padic_galois_counts.m
  padic_filtrations.m
  AllExtensions.m
  JumpSetPack.m
  GenResPack.m
  PolRedPadic/charpoly.m
  PolRedPadic/montes.m
  PolRedPadic/oystein.m
  PolRedPadic/rampoly.m
  PolRedPadic/distinguished.m
}
